version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    stop_signal: SIGINT
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      PORT: 2456
      NAME: "Conceptual Valheim Server"
      WORLD: "SQUAD"
      PASSWORD: "pass1234"
      TZ: "America/Toronto"
      PUBLIC: 0
      AUTO_UPDATE: 0
      AUTO_BACKUP: 1
      AUTO_BACKUP_SCHEDULE: "0 */6 * * *"
      AUTO_BACKUP_REMOVE_OLD: 1
      AUTO_BACKUP_DAYS_TO_LIVE: 3
      AUTO_BACKUP_ON_UPDATE: 1
      AUTO_BACKUP_ON_SHUTDOWN: 1
      UPDATE_ON_STARTUP: 0
      TYPE: BepInExFull
      MODS: |
        https://gcdn.thunderstore.io/live/repository/packages/ValheimModding-Jotunn-2.11.2.zip,
        https://gcdn.thunderstore.io/live/repository/packages/MSchmoecker-MultiUserChest-0.4.4.zip,
        https://gcdn.thunderstore.io/live/repository/packages/MSchmoecker-ItemHopper-0.3.2.zip,
        https://gcdn.thunderstore.io/live/repository/packages/Blockheim-LetMeSleep-1.0.2.zip,
        https://gcdn.thunderstore.io/live/repository/packages/Advize-PlantEverything-1.13.3.zip,
        https://gcdn.thunderstore.io/live/repository/packages/LoadedGun-EquipMultipleUtilityItems-0.4.0.zip


    volumes:
      - ./data/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./data/backups:/home/steam/backups
      - ./data/logs:/home/steam/valheim/logs
      - ./data/config:/home/steam/valheim/BepInEx/config
