version: "3"
services:
  valheim:
    image: mbround18/valheim:1.8
    stop_signal: SIGINT
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      PORT: 2456
      NAME: "Conceptual Valheim Server"
      WORLD: "SQUAD"
      PASSWORD: "pass1234"
      TZ: "America/Toronto"
      PUBLIC: 0
      AUTO_UPDATE: 0
      AUTO_BACKUP: 1
      AUTO_BACKUP_SCHEDULE: "0 */6 * * *"
      AUTO_BACKUP_REMOVE_OLD: 1
      AUTO_BACKUP_DAYS_TO_LIVE: 3
      AUTO_BACKUP_ON_UPDATE: 1
      AUTO_BACKUP_ON_SHUTDOWN: 1
      UPDATE_ON_STARTUP: 0
      TYPE: BepInExFull
      MODS: |
        https://gcdn.thunderstore.io/live/repository/packages/Advize-PlantEverything-1.13.4.zip,
        https://gcdn.thunderstore.io/live/repository/packages/Azumatt-AllTheBases-1.0.5.zip,
        https://gcdn.thunderstore.io/live/repository/packages/Azumatt-AzuAreaRepair-1.0.1.zip,
        https://gcdn.thunderstore.io/live/repository/packages/Azumatt-AzuMiscPatches-1.0.3.zip,
        https://gcdn.thunderstore.io/live/repository/packages/Azumatt-AzuWearNTearPatches-1.0.2.zip,
        https://gcdn.thunderstore.io/live/repository/packages/Azumatt-AzuWorkbenchTweaks-1.0.1.zip,
        https://gcdn.thunderstore.io/live/repository/packages/Marf-FuelEternal-1.2.1.zip,
        https://gcdn.thunderstore.io/live/repository/packages/Azumatt-HaulersHelper-1.0.0.zip
        https://gcdn.thunderstore.io/live/repository/packages/Azumatt-MagicEitrBase-1.1.3.zip,
        https://gcdn.thunderstore.io/live/repository/packages/Azumatt-MaxPlayerCount-1.1.1.zip,
        https://gcdn.thunderstore.io/live/repository/packages/Azumatt-PerfectPlacement-1.0.2.zip,
        https://gcdn.thunderstore.io/live/repository/packages/Blockheim-LetMeSleep-1.0.2.zip,
        https://gcdn.thunderstore.io/live/repository/packages/Digitalroot-Heightmap_Unlimited_Remake-1.3.7.zip,
        https://gcdn.thunderstore.io/live/repository/packages/LoadedGun-EquipMultipleUtilityItems-0.4.0.zip,
        https://gcdn.thunderstore.io/live/repository/packages/MathiasDecrock-PlanBuild-0.13.3.zip,
        https://gcdn.thunderstore.io/live/repository/packages/MSchmoecker-ItemHopper-0.3.2.zip,
        https://gcdn.thunderstore.io/live/repository/packages/MSchmoecker-MultiUserChest-0.4.4.zip,
        https://gcdn.thunderstore.io/live/repository/packages/Smoothbrain-ConfigWatcher-1.0.1.zip,
        https://gcdn.thunderstore.io/live/repository/packages/SpikeHimself-XPortal-1.2.10.zip,
        https://gcdn.thunderstore.io/live/repository/packages/ValheimModding-Jotunn-2.11.3.zip,
        https://gcdn.thunderstore.io/live/repository/packages/VegettaPT-MultiCraft-1.2.0.zip,
        https://gcdn.thunderstore.io/live/repository/packages/nDeavor-PlantAnywhere-0.0.3.zip,
        https://gcdn.thunderstore.io/live/repository/packages/Crystal-FastTools-1.1.2.zip,
        https://gcdn.thunderstore.io/live/repository/packages/Azumatt-AzuExtendedPlayerInventory-1.0.8.zip,
        https://gcdn.thunderstore.io/live/repository/packages/Smoothbrain-Backpacks-1.0.3.zip,
        https://gcdn.thunderstore.io/live/repository/packages/RandyKnapp-EquipmentAndQuickSlots-2.1.5.zip,


    volumes:
      - ./data/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./data/backups:/home/steam/backups
      - ./data/logs:/home/steam/valheim/logs
      - ./data/config:/home/steam/valheim/BepInEx/config
